# @DST-AUTOGENERATED@ CategoryMeta - 由 DevShellTools Studio 自动生成，请勿手工编辑
$script:DstCategoryMeta = [ordered]@{
    files = [PSCustomObject]@{
        编号 = 1
        分类 = "文件管理"
        说明 = "目录浏览、最近修改、目录大小、快速跳转"
        示例 = "dsh files"
    }
    powershell = [PSCustomObject]@{
        编号 = 2
        分类 = "管理员与 PowerShell"
        说明 = "管理员窗口、执行策略、Profile、命令来源"
        示例 = "dsh powershell"
    }
    proxy = [PSCustomObject]@{
        编号 = 3
        分类 = "代理管理"
        说明 = "当前会话代理设置、检查、移除与诊断"
        示例 = "dsh proxy"
    }
    git = [PSCustomObject]@{
        编号 = 4
        分类 = "Git"
        说明 = "状态、分支、提交、拉取、推送、日志和安全预览"
        示例 = "dsh git"
    }
    network = [PSCustomObject]@{
        编号 = 5
        分类 = "网络诊断"
        说明 = "端口、DNS、Ping、HTTP、公网 IP 和端口进程"
        示例 = "dsh network"
    }
}
# @DST-AUTOGENERATED-END@

# @DST-AUTOGENERATED@ HelpData - 由 DevShellTools Studio 自动生成，请勿手工编辑
$script:DstHelpData = @{
    files = @(
        @("lt","最近修改项目，默认 5 个","lt -10"),
        @("ltf","最近修改文件","ltf -10"),
        @("ltd","最近修改目录","ltd -8"),
        @("ll","详细列出目录","ll"),
        @("la","包含隐藏项目","la"),
        @("mkcd","创建并进入目录","mkcd demo"),
        @("up / up2","返回上一级/两级","up2"),
        @("open","资源管理器打开","open ."),
        @("here","显示当前路径","here"),
        @("sz","统计文件或目录大小","sz .")
    )
    powershell = @(
        @("super","打开管理员 PowerShell","super -CurrentDirectory"),
        @("isadmin","检查管理员权限","isadmin"),
        @("psb","当前窗口临时允许脚本","psb"),
        @("reload","重新加载 Profile","reload"),
        @("profile","打开 Profile","profile"),
        @("which","查看命令来源","which codex")
    )
    proxy = @(
        @("lpr set","设置当前会话代理","lpr set http://127.0.0.1:7897"),
        @("lpr test","测试代理端口和联网","lpr test"),
        @("lpr show","查看当前代理","lpr show"),
        @("lpr remove","移除当前代理","lpr remove"),
        @("lpr doctor","综合诊断","lpr doctor"),
        @("lpr clean-user","清理用户级永久代理","lpr clean-user")
    )
    git = @(
        @("gs","Git 状态","gs"),
        @("gb","分支与跟踪关系","gb"),
        @("gco / gsw","切换分支","gsw main"),
        @("gswc","创建并切换分支","gswc feat/demo"),
        @("ga / gaa","暂存文件/全部","gaa"),
        @("gcmsg","提交","gcmsg 'fix: 修复问题'"),
        @("gpp","推送","gpp origin main"),
        @("gpl","仅快进拉取","gpl"),
        @("gf","获取全部远程并清理","gf"),
        @("gg","图形化日志","gg 30"),
        @("gd / gds","未暂存/已暂存差异","gds"),
        @("grv","远程地址","grv"),
        @("gclean","只预览未跟踪清理","gclean")
    )
    network = @(
        @("ports","监听端口和进程","ports"),
        @("port","测试指定 TCP 端口","port 443 github.com"),
        @("myip","查看公网 IP","myip"),
        @("dns","DNS 查询","dns github.com A"),
        @("pingx","有限次数 Ping","pingx github.com 6"),
        @("curlh","查看 HTTP 响应头","curlh https://github.com"),
        @("nettest","基础网络诊断","nettest github.com 443"),
        @("killport","查看/终止端口进程","killport 3000 -Stop")
    )
}
# @DST-AUTOGENERATED-END@

function Show-DstCategories {
    Write-DstTitle "DevShellTools 可用分类"

    $rows = foreach ($key in $script:DstCategoryMeta.Keys) {
        $meta = $script:DstCategoryMeta[$key]
        [PSCustomObject]@{
            编号 = $meta.编号
            分类 = $meta.分类
            关键字 = $key
            中文说明 = $meta.说明
            查看命令 = $meta.示例
        }
    }

    $rows | Format-Table -AutoSize

    Write-Host ""
    Write-Host "使用方式：" -ForegroundColor Cyan
    Write-Host "  dsh                 # 进入交互式分类菜单"
    Write-Host "  dsh list            # 仅列出所有分类"
    Write-Host "  dsh files           # 查看文件管理类全部命令"
    Write-Host "  dsh git             # 查看 Git 类全部命令"
    Write-Host "  dsh help git        # 同样可查看 Git 分类帮助"
    Write-Host "  Get-Help lt -Full   # 查看单个命令详细帮助"
}

function Show-DstCategoryCommands {
    param(
        [Parameter(Mandatory)]
        # @DST-AUTOGENERATED@ CategoryValidateSet - 由 DevShellTools Studio 自动生成
        [ValidateSet("files","powershell","proxy","git","network")]
        # @DST-AUTOGENERATED-END@
        [string]$Category
    )

    $meta = $script:DstCategoryMeta[$Category]
    Write-DstTitle ("分类：" + $meta.分类)
    Write-Host $meta.说明 -ForegroundColor Cyan
    Write-Host ""

    $entries = @(
        foreach ($entry in @($script:DstHelpData[$Category])) {
            # 兼容错误生成的拍平字符串；正常条目为长度≥3的数组
            if ($entry -is [System.Array] -and $entry.Length -ge 3) {
                , $entry
            }
        }
    )
    if ($entries.Count -eq 0) {
        Write-DstWarn "该分类暂无可用命令帮助（或 HelpData 格式异常，请在 Studio 中同步公共部分）。"
        return
    }

    $commandWidth = [Math]::Max(
        16,
        (($entries | ForEach-Object { [string]$_[0] } |
            Measure-Object -Property Length -Maximum).Maximum + 4)
    )

    $descriptionWidth = [Math]::Max(
        30,
        (($entries | ForEach-Object { [string]$_[1] } |
            Measure-Object -Property Length -Maximum).Maximum + 8)
    )

    Write-Host (
        "{0,-$commandWidth}{1,-$descriptionWidth}{2}" -f
        "命令",
        "中文说明",
        "示例"
    ) -ForegroundColor Yellow

    Write-Host (
        "{0,-$commandWidth}{1,-$descriptionWidth}{2}" -f
        ("-" * [Math]::Min($commandWidth - 2, 20)),
        ("-" * [Math]::Min($descriptionWidth - 2, 30)),
        ("-" * 24)
    ) -ForegroundColor DarkGray

    foreach ($entry in $entries) {
        Write-Host (
            "{0,-$commandWidth}{1,-$descriptionWidth}{2}" -f
            [string]$entry[0],
            [string]$entry[1],
            [string]$entry[2]
        )
    }

    Write-Host ""
    Write-Host "查看单命令详细帮助：" -ForegroundColor Cyan
    Write-Host "  Get-Help <命令> -Full"
    Write-Host "示例："
    Write-Host "  Get-Help lt -Examples"
}

function Start-DstMenu {
    while ($true) {
        Show-DstCategories
        Write-Host ""
        Write-Host "0. 退出" -ForegroundColor DarkGray
        $choice = Read-Host "请输入分类编号或关键字"

        switch ($choice.Trim().ToLowerInvariant()) {
            "1" { Show-DstCategoryCommands -Category files }
            "files" { Show-DstCategoryCommands -Category files }
            "文件" { Show-DstCategoryCommands -Category files }

            "2" { Show-DstCategoryCommands -Category powershell }
            "powershell" { Show-DstCategoryCommands -Category powershell }
            "ps" { Show-DstCategoryCommands -Category powershell }

            "3" { Show-DstCategoryCommands -Category proxy }
            "proxy" { Show-DstCategoryCommands -Category proxy }
            "代理" { Show-DstCategoryCommands -Category proxy }

            "4" { Show-DstCategoryCommands -Category git }
            "git" { Show-DstCategoryCommands -Category git }

            "5" { Show-DstCategoryCommands -Category network }
            "network" { Show-DstCategoryCommands -Category network }
            "net" { Show-DstCategoryCommands -Category network }
            "网络" { Show-DstCategoryCommands -Category network }

            "0" { return }
            "q" { return }
            "quit" { return }

            default {
                Write-DstWarn "无效选项。请输入 0-5，或 files / powershell / proxy / git / network。"
            }
        }

        Write-Host ""
        [void](Read-Host "按 Enter 返回分类菜单")
        Clear-Host
    }
}

function dsh {
<#
.SYNOPSIS
DevShellTools 总入口：显示分类菜单、分类命令和版本。
.DESCRIPTION
不带参数时打开交互式分类菜单。也可直接指定分类。
.EXAMPLE
dsh
.EXAMPLE
dsh list
.EXAMPLE
dsh files
.EXAMPLE
dsh git
.EXAMPLE
dsh help network
.EXAMPLE
dsh version
#>
    [CmdletBinding()]
    param(
        [Parameter(Position=0)]
        # @DST-AUTOGENERATED@ ActionValidateSet - 由 DevShellTools Studio 自动生成
        [ValidateSet("menu","list","help","version","files","powershell","proxy","git","network")]
        # @DST-AUTOGENERATED-END@
        [string]$Action = "menu",

        [Parameter(Position=1)]
        # @DST-AUTOGENERATED@ CategoryArgValidateSet - 由 DevShellTools Studio 自动生成
        [ValidateSet("all","files","powershell","proxy","git","network")]
        # @DST-AUTOGENERATED-END@
        [string]$Category = "all"
    )

    switch ($Action) {
        "menu" { Start-DstMenu }
        "list" { Show-DstCategories }
        "version" { "DevShellTools 1.0.5" }
        "files" { Show-DstCategoryCommands -Category files }
        "powershell" { Show-DstCategoryCommands -Category powershell }
        "proxy" { Show-DstCategoryCommands -Category proxy }
        "git" { Show-DstCategoryCommands -Category git }
        "network" { Show-DstCategoryCommands -Category network }
        "help" {
            if ($Category -eq "all") {
                Show-DstCategories
            }
            else {
                Show-DstCategoryCommands -Category $Category
            }
        }
    }
}